INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);

INSERT INTO BOOKS VALUES (SEQ_BOOKS.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (SEQ_AUTHORS.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (SEQ_COMMENTS.NEXTVAL, 'comment text', SEQ_BOOKS.CURRVAL);
INSERT INTO BOOK_AUTHOR VALUES (SEQ_BOOKS.CURRVAL, SEQ_AUTHORS.CURRVAL);





















