INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 1);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 1);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 1);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 1);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 1);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 1);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 1);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 1);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 1);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 1);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 1);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 1);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 1);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 1);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 1);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 1);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 1);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 1);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 1);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 1);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 1);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 1);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 1);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 1);




INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 4);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 4);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 4);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 4);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 4);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 4);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 4);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 4);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 4);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 4);



INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 7);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 7);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 7);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 7);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 7);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 7);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 7);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 7);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 7);

INSERT INTO BOOKS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'description', 'title');
INSERT INTO AUTHORS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'firsN ', 'lastN');
INSERT INTO COMMENTS VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'comment text', 7);

